Add completion to shells
docker/compose-cli pull request #1355
Opened 2021-02-25 22:40 UTC by ulyssessouza

This provides shell completion for `bash`, `fish`, `zsh` and `Powershell`

Resolves https://github.com/docker/compose-cli/issues/1338

2021-03-01 13:22 UTC, ndeloof commented
How to use completion script generated for a subcommand?
How to combine this with docker/cli completion?

2021-03-01 15:50 UTC, ulyssessouza commented on cli/cmd/compose/completion.go
> +`,
@ndeloof 
> How to use completion script generated for a subcommand?
This comes in the help by running `docker compose completion --help`.

> How to combine this with docker/cli completion?
I'm not that sure if I understood well. Do we need to combine that?

2021-03-01 15:57 UTC, thaJeztah commented
Wondering if instead of a subcommand, we should use a `--completion` flag (`--completion=bash`); this command is very unlikely to be used by the user itself (more a "set and forget" options somewhere in a `.profile`), but being a `command` could by itself make it end up in completion suggestions

2021-03-01 15:57 UTC, gtardif commented
As discussed previously with @ulyssessouza , we need to find a better way to integrate with completion scripts shipped / installed with Docker Desktop. (Desktop actually includes completion scripts for the docker CLI and for `docker-compose`)

Completion scripts for the docker CLI include many examples of completion for subcommands, we can adapt this. 
for the cli & docker-compose, completion scripts are packages next to the binary and Desktop re-packages this for it's install)

2021-03-02 14:00 UTC, ndeloof requested changes
need to clarify how this would impact the docker CLI completion scripts

2021-03-03 12:44 UTC, ulyssessouza commented
PTAL at https://github.com/docker/compose-cli/pull/1384

This alternative PR builds an external binary to generate the completion files. This avoid polluting the "compose business" with technical stuff.
It also integrates the generation to the normal build so that when running `make` it also generates the completion files bin the `bin` directory side-by-side with the binary.

2021-03-04 04:07 UTC, closed without merging