Add `compose top` command
docker/compose-cli pull request #1398
Opened 2021-03-05 11:45 UTC by aiordache

Implement `compose top`.

```

$ docker compose top
compose-cli_web_1
UID    PID     PPID    C    STIME   TTY   TIME       CMD
root   73864   73803   0    10:24   ?     00:00:00   nginx: master process nginx -g daemon off;   
101    74422   73864   0    10:24   ?     00:00:00   nginx: worker process                        

compose-cli_web_2
UID    PID     PPID    C    STIME   TTY   TIME       CMD
root   73863   73784   0    10:24   ?     00:00:00   nginx: master process nginx -g daemon off;   
101    74230   73863   0    10:24   ?     00:00:00   nginx: worker process                        

compose-cli_web_3
UID    PID     PPID    C    STIME   TTY   TIME       CMD
root   73862   73823   0    10:24   ?     00:00:00   nginx: master process nginx -g daemon off;   
101    74400   73862   0    10:24   ?     00:00:00   nginx: worker process                        

```
```
$ docker-compose top
compose-cli_web_1
UID     PID    PPID    C   STIME   TTY     TIME                        CMD                    
----------------------------------------------------------------------------------------------
root   73864   73803   0   10:24   ?     00:00:00   nginx: master process nginx -g daemon off;
101    74422   73864   0   10:24   ?     00:00:00   nginx: worker process                     

compose-cli_web_2
UID     PID    PPID    C   STIME   TTY     TIME                        CMD                    
----------------------------------------------------------------------------------------------
root   73863   73784   0   10:24   ?     00:00:00   nginx: master process nginx -g daemon off;
101    74230   73863   0   10:24   ?     00:00:00   nginx: worker process                     

compose-cli_web_3
UID     PID    PPID    C   STIME   TTY     TIME                        CMD                    
----------------------------------------------------------------------------------------------
root   73862   73823   0   10:24   ?     00:00:00   nginx: master process nginx -g daemon off;
101    74400   73862   0   10:24   ?     00:00:00   nginx: worker process 
```

2021-03-05 13:33 UTC, ndeloof requested changes
use of `ignore` func can be avoided

2021-03-05 13:33 UTC, ndeloof commented on local/compose/top.go
> +	ignore := func(string) bool {
you don't need this, use `containers.filter(isService(services...))`

2021-03-05 14:04 UTC, gtardif requested changes
LGTM, but with a quick e2e test (after one of the existing compose up) for this command

2021-03-05 14:04 UTC, gtardif commented on cli/cmd/compose/top.go
> +	}
You could extract this in a function to unit test it (will need a variable for stdout)

2021-03-08 10:17 UTC, gtardif approved these changes

2021-03-08 10:25 UTC, ndeloof approved these changes

2021-03-08 10:25 UTC, merged