Set image digest as service image to trigger recreation after build
docker/compose-cli pull request #1530
Opened 2021-04-13 09:42 UTC by aiordache

When an image is updated locally via pull or build, the containers are not being recreated on `compose up` (service hash is not generated with the image digest but with an image repo/tag that could be reassigned on build).

This fixes also the output of `compose images` when the repo/tag changes (aligns with docker-compose).

```
[example]$ docker compose up -d
[+] Running 3/3
 ⠿ Container example_backend_1   Running                                                                                                           0.0s
 ⠿ Container example_backend_2   Running                                                                                                           0.0s
 ⠿ Container example_frontend_1  Running                                                                                                           0.6s
```
```
[example]$ docker compose images
Container            Repository          Tag                 Image Id            Size
example_backend_1    nginx               latest              515ea3e0d096        133MB
example_backend_2    nginx               latest              515ea3e0d096        133MB
example_frontend_1   example_frontend    latest              a7063fa9db03        22.6MB
```
```
[example]$ docker compose build
[+] Building 0.4s (7/7) FINISHED                                                                                                                        
 => [internal] load build definition from Dockerfile                                                                                               0.0s
 => => transferring dockerfile: 102B                                                                                                               0.0s
 => [internal] load .dockerignore                                                                                                                  0.0s
 => => transferring context: 2B                                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/nginx:alpine                                                                                    0.4s
 => [internal] load build context                                                                                                                  0.0s
 => => transferring context: 31B                                                                                                                   0.0s
 => [1/2] FROM docker.io/library/nginx:alpine@sha256:d942e5263869b00ed3174fb76573165dc89e391bfafa43e9134a9c6e0bf0ec87                              0.0s
 => CACHED [2/2] COPY nginx.conf /etc/nginx/conf.d/default.conf                                                                                    0.0s
 => exporting to image                                                                                                                             0.0s
 => => exporting layers                                                                                                                            0.0s
 => => writing image sha256:465f434f2e6a5972145b27945d8c157d5514c981895cc351c0c3c04533b870d4                                                       0.0s
 => => naming to docker.io/library/example_frontend                                                                                                0.0s
```
```
[example]$ docker compose images
Container            Repository          Tag                 Image Id            Size
example_backend_1    nginx               latest              515ea3e0d096        133MB
example_backend_2    nginx               latest              515ea3e0d096        133MB
example_frontend_1   <none>              <none               a7063fa9db03        22.6MB
```
```
[example]$ docker compose up -d
[+] Running 3/3
 ⠿ Container example_backend_1   Running                                                                                                           0.0s
 ⠿ Container example_backend_2   Running                                                                                                           0.0s
 ⠿ Container example_frontend_1  Started                                                                                                           0.8s
```
```
[example]$ docker compose images
Container            Repository          Tag                 Image Id            Size
example_backend_1    nginx               latest              515ea3e0d096        133MB
example_backend_2    nginx               latest              515ea3e0d096        133MB
example_frontend_1   example_frontend    latest              465f434f2e6a        22.6MB

```

Fixes https://github.com/docker/compose-cli/issues/1521

2021-04-13 09:54 UTC, ndeloof commented on cli/cmd/compose/images.go
> +					tag = "<none"
typo `<none` -> `<none>`

2021-04-13 10:01 UTC, ndeloof approved these changes
could be made simpler using buildx exporter response `containerimage.digest`

2021-04-13 10:01 UTC, ndeloof commented on local/compose/build.go
> +	images, err := s.getImages(ctx, imageNames)
you don't need this
on build we ignore buildx response (line 197 `<response>, err = build.Build(...)`)
same as https://github.com/docker/app/blob/9d2c67f87b7338eb1a0fa2f18eb81af3d2aac0e1/internal/commands/build/build.go#L340 you can get the image digest and update the service configuration accordingly, no need to inspect image post-build.

2021-04-13 10:02 UTC, ndeloof requested changes
could be made simpler using buildx exporter response `containerimage.digest`

2021-04-19 10:48 UTC, gtardif commented
Fix LGTM ; maybe with this fix we don't need anymore some changes introduced in #1464 to ensure recreation of containers after rebuild of images

2021-04-20 07:36 UTC, ndeloof approved these changes
LGTM with a question on parallelism removal

2021-04-20 07:36 UTC, ndeloof commented on local/compose/build.go
> +		if !utils.StringContains(imageNames, imgName) {
could use the `map[string]` you just create few lines later to check already resolved image

2021-04-20 07:36 UTC, ndeloof commented on local/compose/images.go
> +		inspect, _, err := s.apiClient.ImageInspectWithRaw(ctx, img)
why did you removed parallelism on this API call?

2021-04-20 16:16 UTC, gtardif approved these changes

2021-04-20 19:05 UTC, merged