publish cross platform artifacts for PRs
docker/compose-cli pull request #2041
Opened 2021-08-25 08:40 UTC by ndeloof

**What I did**
Build cross platform binaries and publish artifacts as part of PR builds to make it easier testing changes

2021-08-25 13:45 UTC, ulyssessouza requested changes
I think we should have any mechanism to trigger that and not just generate the artifacts for all the PRs.

Maybe using something like the "/test-aci" tag to enable tests on ACI, for example.
A `/generate-artifacts` would be nice!

2021-08-25 14:31 UTC, ndeloof commented
/generate-artifacts

2021-08-25 14:33 UTC, ndeloof commented
/generate-artifacts

2021-08-25 14:37 UTC, ndeloof commented
/generate-artifacts

2021-08-25 14:38 UTC, ndeloof commented
/generate-artifacts

2021-08-25 15:06 UTC, ndeloof commented
@ulyssessouza makes sense.
unfortunately, this makes it harder to retrieve the matching GA workflow run to get binaries

2021-08-25 15:21 UTC, ndeloof commented
Added an extra step to update the PR comment with a link to workflow run page, so that user can access built binaries
see sample run on https://github.com/ndeloof/compose-cli/pull/4

2021-08-30 11:43 UTC, mat007 approved these changes
Nice!

2021-08-30 11:43 UTC, mat007 commented on .github/workflows/pending_answered.yml
> +name: Remove pending lable on answer
```suggestion
name: Remove pending label on answer
```

2021-08-30 11:43 UTC, mat007 commented on .github/workflows/artifacts.yml
> +            This PR can be tested using [binaries](https://github.com/docker/compose-cli/actions/runs/${{ github.run_id }})
```suggestion
            This PR can be tested using [binaries](https://github.com/docker/compose-cli/actions/runs/${{ github.run_id }}).
```

2021-08-30 12:46 UTC, merged