redirect compose v2 users to github.com/docker/compose
docker/compose-cli pull request #2065
Opened 2021-09-02 14:01 UTC by ndeloof

**What I did**

Document Compose V2 code has moved to github.com/docker/compose

2021-09-02 15:47 UTC, stephanierifai requested changes
LGTM added small changes just to make it clear in the header the code has moved

2021-09-02 15:47 UTC, stephanierifai commented on README.md
> +## :warning: Compose v2 (a.k.a "Local Docker Compose")
```suggestion
## :warning: Compose v2 (a.k.a "Local Docker Compose") has Moved
```

2021-09-02 15:47 UTC, stephanierifai commented on README.md
> +This repository is about "Cloud Integrations", if you're looking for Docker Compose v2,
```suggestion
This repository is about "Cloud Integrations", the Docker Compose v2
```

2021-09-03 09:14 UTC, lorenrh approved these changes

2021-09-03 09:15 UTC, merged